### ISSUE TITLE
Collaborate request

### ISSUE THREAD

**Issue by liaojason2** [LeeLin2602/cloudnative-hw#2]
If you accept, we can do future hw together.
![Programming_  by 3hil on DeviantArt](https://user-images.githubusercontent.com/46263348/166429196-22519c05-81cb-444f-8a76-8f1f81c6c5ba.jpg)

**Comment by wdzeng** [comment]
![20200216_5e49636e359ea](https://user-images.githubusercontent.com/39057640/166569937-7ea030ac-4ea2-4faf-b8d2-d26c3f74abd5.jpg)

**Comment by liaojason2** [comment]
🤔
